version: "3"

services:
        db:
          ports:
            - '0.0.0.0:5432:5432'
          env_file: .env
          environment:
                  - POSTGRES_HOST_AUTH_METHOD:"trust"
                  - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
                  - POSTGRES_USER:${POSTGRES_USER}
                  - POSTGRES_DB:${POSTGRES_DB}
          build:
                context: .
                dockerfile: Dockerfile
          image: postgres
          restart: always
        web:
           build:
                context: .
                dockerfile: Dockerfile
           command: uvicorn main:app --host 0.0.0.0 --reload
           volumes:
               - .:/take_home
           ports:
              - 8000:80
           links:
             - db
           restart: on-failure
